# Generated by Django 6.0.2 on 2026-03-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_user_commentary_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='author',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='owner',
        ),
    ]
