# Generated by Django 6.0.2 on 2026-03-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_author_commentary_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='owner',
            new_name='user',
        ),
    ]
